#!/bin/bash
#SBATCH --job-name=FinNLP-GPT2-QA_newsplit-v1-6epoch
#SBATCH --account=project_2001403
#SBATCH --partition=gpu
#SBATCH --time=42:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10
#SBATCH --mem-per-cpu=16000
#SBATCH --gres=gpu:v100:2
#SBATCH --mail-user=ilmari.kylliainen@helsinki.fi
#SBATCH --output=FinNLP-GPT2-QA_newsplit-v1-6epoch.log
#SBATCH --mail-type=BEGIN,END,FAIL

module purge

module load pytorch/1.9

srun python ../fine_tune_FNLP_gpt_qa.py --epochs 6 --exp FinNLP-GPT2-newsplit-QA-v1